development: &defaults
  adapter: postgresql
  encoding: unicode
  database: ENV['APP_NAME'] + "_development" 
  pool: 5
  host: localhost
  username: ENV['PG_USER_DEV'] 
  password: 

test:
  <<: *defaults
  database: ENV['APP_NAME'] + "_test" 

production:
  <<: *defaults
  database: ENV['APP_NAME'] + "_production" 
