development: &defaults
  adapter: postgresql
  encoding: unicode
  database: ENV['APP_NAME'] + "_development" 
  pool: 5
  host: localhost

test:
  <<: *defaults
  database: ENV['APP_NAME'] + "_test" 

production:
  <<: *defaults
  database: ENV['APP_NAME'] + "_production" 
