development: &defaults
  adapter: postgresql
  encoding: unicode
  database: APP_NAME_development
  pool: 5
  host: localhost
  username: YOUR_USERNAME 
  password: 

test:
  <<: *defaults
  database: APP_NAME_test

production:
  <<: *defaults
  database: APP_NAME_production
