development: &defaults
  adapter: postgresql
  database: <%= ENV['APP_NAME'] %>_development
  pool: 5
  host: localhost

test:
  <<: *defaults
  database: <%= ENV['APP_NAME'] %>_test 

production:
  <<: *defaults
  database: <%= ENV['APP_NAME'] %>_production 
